#!/usr/bin/perl
#
my %vals=();
my %multiplier = ('p' => 1e-12, 'n' => 1e-9, 'u' => 1e-6, 'm' => 1e-3,
                  'k' => 1e3, 'M' => 1e6, 'g' => 1e12,
                  'P' => 1e-12, 'N' => 1e-9, 'U' => 1e-6,
                  'K' => 1e3, 'G' => 1e12 );
while (<>) {
  chomp;
  
  my($val,$fp,$tol,$pow,$pn)=split(/\|/,$_);
  $val=stripwhite($val);
  #printf("%s => %g\n",$val,tonumeric($val));
  $vals{$val}=1 if (length($val));
}

my @valList=sort byval (keys(%vals));

for (my $j=0; $j<scalar(@valList); $j++) {
  print $valList[$j],"\n";
}

exit;

sub stripwhite {
  my $in=shift;

  $in=~s/^\s+//;
  $in=~s/\s+$//;
  return($in);
}

sub byval {
  my $aval=tonumeric($a);
  my $bval=tonumeric($b);
  return($aval <=> $bval);
}

sub tonumeric {
  my $val=shift;

  my $value="NAN";
  if ($val=~/([0-9.-]+[eE]?[0-9-]*)\s*([pnumkMgPNUKG])?/) {
     if ($multiplier{$2}) {
        $value=$1 * $multiplier{$2};
     } else {
        $value=$1 * 1.0;
    }
  }

  return($value);
}
